import { REACT_SERVER_URL } from '@env';

//172.20.10.3
//192.168.1.36
export const SERVER_URL = __DEV__
  ? 'http://192.168.1.36:3001'
  : REACT_SERVER_URL;
export const API_URL = `${SERVER_URL}/api`;

export const QUERY_KEYS = {
  FETCH_CHATS: 'FETCH_CHATS',
  FETCH_SUPPORT_ALL_CLIENT_CHATS: 'FETCH_SUPPORT_ALL_CLIENT_CHATS',
  FETCH_SUPPORT_ALL_STORE_CHATS: 'FETCH_SUPPORT_ALL_STORE_CHATS',
  FETCH_MEMBER_CHATS: 'FETCH_MEMBER_CHATS',
  FETCH_LATEST_MESSAGES: 'FETCH_LATEST_MESSAGES',
  FETCH_RECENTLY_MESSAGES: 'FETCH_RECENTLY_MESSAGES',
};

export const FLASH_STALE_TIME = 300;
export const SHORT_STALE_TIME = 1000;

export enum STATUS {
  SUCCESS = 200,
  CREATED = 201,
  NO_CONTENT = 204,
  CLIENT_ERRORS = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  UNPROCESSABLE = 422,
  SERVER_ERRORS = 500,
}
